CREATE TABLE User (
Id LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
Username VARCHAR(50) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL
);

INSERT INTO User (UserName, FirstName, LastName) VALUES ('bcos96','Cosmin', 'Bresug');