CREATE TABLE User (
Id LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
Username VARCHAR(50) NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL
);

CREATE TABLE User (
Id LONG PRIMARY KEY AUTO_INCREMENT NOT NULL,
Balance LONG NOT NULL,
OwnerID LONG NOT NULL,
Currency VARCHAR(50) NOT NULL
);